### ISSUE TITLE
Not support  SqlServer or Oracle

### ISSUE THREAD

**Issue by cnxy** [zzzprojects/Z.ExtensionMethods#16]
Why not write the extension of SqlServer or Oracle?

**Comment by JonathanMagnan** [comment]
What kind of extension method are you looking for?

**Comment by cnxy** [comment]
@JonathanMagnan 
Such as
```csharp
public static partial class Extensions
{
    public static DataSet ExecuteDataSet(this SqlCommand @this)
    {
        var ds = new DataSet();
        using (var dataAdapter = new SqlDataAdapter(@this))
        {
            dataAdapter.Fill(ds);
        }
        return ds;
    }
}
```

But Not In This Extension.

**Comment by JonathanMagnan** [comment]
Hello @cnxy ,

I will close this request since we have no plan to add extension methods for `Oracle` at this moment.

We have some great plan for this library in `2019` so it might happen but for now, we prefer to start to work on the documentation first before adding more extension methods.

Best Regards,

Jonathan
