### ISSUE TITLE
Needs documentation

### ISSUE THREAD

**Issue by Arithmomaniac** [zzzprojects/Z.ExtensionMethods#17]
There's no easy way to figure out what is in this package, given all of the overloads. Even [disassembly](http://dotnetapis.com/pkg/Z.ExtensionMethods/2.1.0/netstandard2.0/doc/.Extensions) yields too many methods.

I like how [MoreLINQ](https://github.com/morelinq/MoreLINQ#operators) handles this.

**Comment by JonathanMagnan** [comment]
Hello @Arithmomaniac ,

We have way more extension methods than `MoreLINQ`, so I don't think we can handle it the same way.

We already created in the past an online documentation but it has been removed. We will probably try again to maybe do something similar to http://extensionmethod.net/ but there is no short-term plan for this.

**Comment by starikcetin** [comment]
You can at least list them out using an automated documenting software.

**Comment by JonathanMagnan** [comment]
Hello @Arithmomaniac ,

Good news, we finally choose to have a developer dedicated to the document in January and create a website for the documentation about our extensions methods.

Every extension methods will come with documentation and an online example using https://dotnetfiddle.net/ whenever we can.

**Comment by JonathanMagnan** [comment]
Hello @Arithmomaniac ,

A website has been created this month: https://csharp-extension.com/

A lot of online examples can be found here: https://csharp-extension.com/en/online-example/

It's not near to be completed but we work on it on daily basis. We will probably improve a lot the layout next week when my design will be back from the vacancy.

I will close this request since we pretty much work on it ;)
