### ISSUE TITLE
BinaryFormatter serialization and deserialization are disabled

### ISSUE THREAD

**Issue by alonstar** [zzzprojects/Z.ExtensionMethods#33]
Hi,

I upgraded to .net 5.0 and found "BinaryFormatter serialization and deserialization are disabled" in aspnet core.

the DeepClone method throws exception.

BinaryFormatter serialization and deserialization are disabled within this application. See https://aka.ms/binaryformatter for more information.

**Comment by JonathanMagnan** [comment]
Hello @alonstar ,

Sorry for the long delay,

Unfortunately, I don't think we will do anything here,

You can re-enable it this way:

```xml
<PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <EnableUnsafeBinaryFormatterSerialization>true</EnableUnsafeBinaryFormatterSerialization>
</PropertyGroup>
```

Honestly, we don't agree with `Microsoft` decision on this. If you know what you are doing, there is nothing dangerous. That's no more dangerous than doing some bad code with a SQL Command. The scenario they provide in the section `The risks of assuming data to be trustworthy` are pretty much extreme and kind of scenario I would not have recommended doing.

For backward compatibility and because other serializers in the "Preferred alternatives" doesn't do exactly what the `BinaryFormatter` do, we prefer to let the code like this

Best Regards,

Jon

---
**Sponsorship**
[Help us improve this library](https://github.com/sponsors/zzzprojects)

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](https://entityframework-extensions.net/) • [Bulk Operations](https://bulk-operations.net/) •  [Dapper Plus](https://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](https://eval-expression.net/) • [SQL Eval Function](https://eval-sql.net/)
