### ISSUE TITLE
the `useDefaultIfNull` paramter in `ToCharOrDefault` method is useless

### ISSUE THREAD

**Issue by Sunzhuokai** [zzzprojects/Z.ExtensionMethods#8]
https://github.com/zzzprojects/Z.ExtensionMethods/blob/master/src/Z.Core/System.Object/Convert/ToValueType/Object.ToCharOrDefault.cs#L53
`Convert.ToChar(null)` will throw a `ArgumentNullException`，So no matter the `useDefaultIfNull`  is `true` or `false`  the defaultValue always return

**Comment by Sunzhuokai** [comment]
Same as `Guid`

**Comment by JonathanMagnan** [comment]
Hello @Sunzhuokai ,

Thank you for reporting,

We will look at it since the pull provided seems to change the default behavior.

Best Regards,

Jonathan

---
_Help us to keep this library free: [Donate](http://www.zzzprojects.com/contribute)_

**Comment by JonathanMagnan** [comment]
Hello @Sunzhuokai ,

After investigating this issue, we found at that

```csharp
Convert.ToChar(null)
```

throw an error since the `null` constant is used.

However, when using a variable such as

```csharp
object obj = null;
var ch = Convert.ToChar(obj);
```

No error is thrown.

Unless I'm wrong, the method works as intended and adding the change from your pull will do nothing since a `parameter` is used and not a `null` constant.

Let me know if the explanation is clear enough .

Best Regards,

Jonathan

---
_Help us to keep this library free: [Donate](http://www.zzzprojects.com/contribute)_

**Comment by Sunzhuokai** [comment]
I mean the 'useDefaultIfNull' parameter is useless
```csharp
object obj = null;
obj.ToCharOrDefault('a',true); // return 'a'
obj.ToCharOrDefault('a',false);  // return 'a'

```

**Comment by JonathanMagnan** [comment]
Hello @Sunzhuokai ,

That's not what my test is returning me.

```csharp
object obj = null;
var ch1 = obj.ToCharOrDefault('a', true); // return 'a'
var ch2 = obj.ToCharOrDefault('a', false);  // return '\0'
```

There is a big difference on my side.

Best Regards,

Jonathan

**Comment by Sunzhuokai** [comment]
you are right
